#%RAML 1.0
title: COS Test API

/login:
  post:
    body:
      application/json: 
        example: |
          {"username": "ER38sd","passowrd": "400"}

    responses:
      200:
        body:
          application/json:
            example: |
              {"data": "success"}

/registry:
  post:
    body:
      application/json: 
        example: |
          {"username": "ER38sd","passowrd": "400"}

    responses:
      200:
        body:
          application/json:
            example: |
              {"data": "success"}
              
/apps:
  post:
    body:
      application/json: 
        example: |
          {"username": "ER38sd","passowrd": "400"}

    responses:
      200:
        body:
          application/json:
            example: |
              {"data": "success"}
              
/app-detail:
  post:
    body:
      application/json: 
        example: |
          {"username": "ER38sd","passowrd": "400"}

    responses:
      200:
        body:
          application/json:
            example: |
              {"data": "success"}
              
/save-app:
  post:
    body:
      application/json: 
        example: |
          {"username": "ER38sd","passowrd": "400"}

    responses:
      200:
        body:
          application/json:
            example: |
              {"data": "success"}
              
/username-check:
  post:
    body:
      application/json: 
        example: |
          {"username": "ER38sd","passowrd": "400"}

    responses:
      200:
        body:
          application/json:
            example: |
              {"data": "success"}